"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

License
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _BriarError:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BriarErrorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BriarError.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BRIAR_SUCCESS: _BriarError.ValueType  # 0
    """No error"""
    BRIAR_UNKNOWN_ERROR: _BriarError.ValueType  # 1
    """Catch all error code"""
    BRIAR_INTERNAL_ERROR: _BriarError.ValueType  # 2
    """An internal SDK error was encountered"""
    BRIAR_OUT_OF_MEMORY: _BriarError.ValueType  # 3
    """Out of memory error"""
    BRIAR_INVALID_SDK_PATH: _BriarError.ValueType  # 4
    """Invalid SDK location"""
    BRIAR_BAD_SDK_CONFIG: _BriarError.ValueType  # 5
    """Invalid SDK configuration"""
    BRIAR_BAD_LICENSE: _BriarError.ValueType  # 6
    """Incorrect license file"""
    BRIAR_MISSING_DATA: _BriarError.ValueType  # 7
    """Missing SDK data"""
    BRIAR_INVALID_GPU: _BriarError.ValueType  # 8
    """The GPU is not functioning"""
    BRIAR_BAD_ARGUMENT: _BriarError.ValueType  # 9
    """An argument to a BRIAR function is invalid"""
    BRIAR_OPEN_ERROR: _BriarError.ValueType  # 10
    """Failed to open a file"""
    BRIAR_READ_ERROR: _BriarError.ValueType  # 11
    """Failed to read from a file"""
    BRIAR_WRITE_ERROR: _BriarError.ValueType  # 12
    """Failed to write to a file"""
    BRIAR_PARSE_ERROR: _BriarError.ValueType  # 13
    """Failed to parse a file"""
    BRIAR_INVALID_MEDIA: _BriarError.ValueType  # 14
    """Failed to decode a media file"""
    BRIAR_OUT_OF_BOUNDS_ACCESS: _BriarError.ValueType  # 15
    """Out of bounds access into a buffer"""
    BRIAR_MEDIA_AT_END: _BriarError.ValueType  # 16
    """Media object is at the end of its data"""
    BRIAR_INVALID_ATTRIBUTE_KEY: _BriarError.ValueType  # 17
    """An invalid attribute key was provided"""
    BRIAR_MISSING_ATTRIBUTE: _BriarError.ValueType  # 18
    """A value for a valid attribute key is not present"""
    BRIAR_DUPLICATE_ID: _BriarError.ValueType  # 19
    """Template id already exists in a gallery"""
    BRIAR_MISSING_ID: _BriarError.ValueType  # 20
    """Template id can't be found"""
    BRIAR_MISSING_FILE_NAME: _BriarError.ValueType  # 21
    """An expected file name is not given"""
    BRIAR_INCORRECT_ROLE: _BriarError.ValueType  # 22
    """Incorrect template role"""
    BRIAR_FAILURE_TO_SERIALIZE: _BriarError.ValueType  # 23
    """Could not serialize a data structure"""
    BRIAR_FAILURE_TO_DESERIALIZE: _BriarError.ValueType  # 24
    """Could not deserialize a data structure"""
    BRIAR_BATCH_ABORTED_EARLY: _BriarError.ValueType  # 25
    """Batch call aborted early due to error"""
    BRIAR_BATCH_FINISHED_WITH_ERRORS: _BriarError.ValueType  # 26
    """Batch call finished, but with errors"""
    BRIAR_CALLBACK_EXIT_IMMEDIATELY: _BriarError.ValueType  # 27
    """Callback error indicating processing should stop immediately"""
    BRIAR_NOT_IMPLEMENTED: _BriarError.ValueType  # 28
    """Optional function return"""
    BRIAR_NUM_ERRORS: _BriarError.ValueType  # 29
    """Utility to iterate over all errors"""

class BriarError(_BriarError, metaclass=_BriarErrorEnumTypeWrapper):
    """Enum to define the different Briar error codes"""

BRIAR_SUCCESS: BriarError.ValueType  # 0
"""No error"""
BRIAR_UNKNOWN_ERROR: BriarError.ValueType  # 1
"""Catch all error code"""
BRIAR_INTERNAL_ERROR: BriarError.ValueType  # 2
"""An internal SDK error was encountered"""
BRIAR_OUT_OF_MEMORY: BriarError.ValueType  # 3
"""Out of memory error"""
BRIAR_INVALID_SDK_PATH: BriarError.ValueType  # 4
"""Invalid SDK location"""
BRIAR_BAD_SDK_CONFIG: BriarError.ValueType  # 5
"""Invalid SDK configuration"""
BRIAR_BAD_LICENSE: BriarError.ValueType  # 6
"""Incorrect license file"""
BRIAR_MISSING_DATA: BriarError.ValueType  # 7
"""Missing SDK data"""
BRIAR_INVALID_GPU: BriarError.ValueType  # 8
"""The GPU is not functioning"""
BRIAR_BAD_ARGUMENT: BriarError.ValueType  # 9
"""An argument to a BRIAR function is invalid"""
BRIAR_OPEN_ERROR: BriarError.ValueType  # 10
"""Failed to open a file"""
BRIAR_READ_ERROR: BriarError.ValueType  # 11
"""Failed to read from a file"""
BRIAR_WRITE_ERROR: BriarError.ValueType  # 12
"""Failed to write to a file"""
BRIAR_PARSE_ERROR: BriarError.ValueType  # 13
"""Failed to parse a file"""
BRIAR_INVALID_MEDIA: BriarError.ValueType  # 14
"""Failed to decode a media file"""
BRIAR_OUT_OF_BOUNDS_ACCESS: BriarError.ValueType  # 15
"""Out of bounds access into a buffer"""
BRIAR_MEDIA_AT_END: BriarError.ValueType  # 16
"""Media object is at the end of its data"""
BRIAR_INVALID_ATTRIBUTE_KEY: BriarError.ValueType  # 17
"""An invalid attribute key was provided"""
BRIAR_MISSING_ATTRIBUTE: BriarError.ValueType  # 18
"""A value for a valid attribute key is not present"""
BRIAR_DUPLICATE_ID: BriarError.ValueType  # 19
"""Template id already exists in a gallery"""
BRIAR_MISSING_ID: BriarError.ValueType  # 20
"""Template id can't be found"""
BRIAR_MISSING_FILE_NAME: BriarError.ValueType  # 21
"""An expected file name is not given"""
BRIAR_INCORRECT_ROLE: BriarError.ValueType  # 22
"""Incorrect template role"""
BRIAR_FAILURE_TO_SERIALIZE: BriarError.ValueType  # 23
"""Could not serialize a data structure"""
BRIAR_FAILURE_TO_DESERIALIZE: BriarError.ValueType  # 24
"""Could not deserialize a data structure"""
BRIAR_BATCH_ABORTED_EARLY: BriarError.ValueType  # 25
"""Batch call aborted early due to error"""
BRIAR_BATCH_FINISHED_WITH_ERRORS: BriarError.ValueType  # 26
"""Batch call finished, but with errors"""
BRIAR_CALLBACK_EXIT_IMMEDIATELY: BriarError.ValueType  # 27
"""Callback error indicating processing should stop immediately"""
BRIAR_NOT_IMPLEMENTED: BriarError.ValueType  # 28
"""Optional function return"""
BRIAR_NUM_ERRORS: BriarError.ValueType  # 29
"""Utility to iterate over all errors"""
global___BriarError = BriarError

@typing.final
class BriarErrors(google.protobuf.message.Message):
    """List of errors"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERRORS_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    length: builtins.int
    """Number of Error codes"""
    @property
    def errors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___BriarError.ValueType]:
        """Error codes"""

    def __init__(
        self,
        *,
        errors: collections.abc.Iterable[global___BriarError.ValueType] | None = ...,
        length: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["errors", b"errors", "length", b"length"]) -> None: ...

global___BriarErrors = BriarErrors

@typing.final
class BriarErrorMessage(google.protobuf.message.Message):
    """Human readable Error message with code"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_code: builtins.int
    """Error Code"""
    error_message: builtins.str
    """Human readable string"""
    def __init__(
        self,
        *,
        error_code: builtins.int = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "error_message", b"error_message"]) -> None: ...

global___BriarErrorMessage = BriarErrorMessage
